---
title: "04-08"
author: "林茂廷"
date: "4/7/2020"
output: html_document
---

# 4.1 選取元素

## 4.1.1 選「一個元素」

```{r}
vectorExample <- c("小明","小英","大雄")

# 有多少位置可選：
length(vectorExample)
```
```{r}
vectorExample[[1]]
vectorExample[[3]]
```
```{r}
listExample <- 
  list(
    student="小明",
    `學期`=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )
# 有多少位置可選：
length(listExample)
```

```{r}
listExample1 <- listExample[[1]]
print(listExample1)
```

```{r}
listExample2 <- listExample[[2]]
print(listExample2)
```

```{r}
str(listExample2)
listExample2[[1]]
listExample2[[2]]
```


```{r}
library(jsonlite)
fromJSON("https://data.tainan.gov.tw/dataset/4cd9345a-04bf-4328-a97d-314ff78b4763/resource/afc025fc-1ef4-447c-b785-a680391d0ca1/download/tnsport2.json", simplifyDataFrame = F) -> tainanSportsMap
```

```{r}
length(tainanSportsMap)
```
```{r}
str(tainanSportsMap[[1]])
str(tainanSportsMap[[1076]])
```


```{r}
str(listExample)
```

```{r}
listExample$student
listExample$`學期` # 特殊命名依然要用反頓點呼叫

str(listExample$`學期`)
```
```{r}
fromJSON("http://data.ntpc.gov.tw/api/v1/rest/datastore/382000000A-000157-002",
         simplifyDataFrame = F) -> newTaipeiCityVaccine

str(newTaipeiCityVaccine,
    max.level = 1)
```

```{r}
listExample[["student"]]
listExample$student

listExample[["學期"]] # 小心不是反頓點喔。
listExample$`學期`
```


## 4.1.2 選「多個元素」

```{r}
vectorExample
vectorExample[c(1,3)]
vectorExample[c(3,2,1)] # 產生重新排列效果
```


```{r}
vectorExample[c(1,3)]
vectorExample[c(3,2,1)] # 產生重新排列效果
```
```{r}
# 顯示到第一層
str(listExample, max.level=1)

listExample[c(2,1)] -> listExample3
```

```{r}
# 顯示到第一層
str(listExample, max.level=1)
# 顯示到第一層
str(listExample3, max.level=1)

```
```{r}
# 顯示到第一層
str(listExample, max.level=1)

listExample[c("學期")]
listExample[c("student","學期")]
```

```{r}
fromJSON("https://www.dropbox.com/s/qnm9bnz7vccrvcz/taipeiNightMarkets.json?dl=1", simplifyDataFrame = F) -> taipeiNightMarkets
```

```{r}
str(taipeiNightMarkets)

length(taipeiNightMarkets)
names(taipeiNightMarkets)
```

```{r}
vectorExample
vectorExample[c(T,T,F)] # 要，要，不要
```
```{r}
str(listExample, max.level = 2)
```

[[]]
```{r}
get1 <- listExample[["學期"]]
str(get1, max.level=2)
```
```{r}
str(listExample, max.level = 2)
```
[]
```{r}
get2 <- listExample["學期"]
str(get2, max.level=2)
```

## 4.1.3 連鎖選取 

```{r}
numVector <- c(2,3,6,-1,4,2,6)
select1 <- numVector[c(1,4)]; select1
select2 <- select1[[1]]; select2

# 相當於
numVector[c(1,4)][[1]]
```

```{r}
select2 <- select1[[1]]; select2
```
```{r}
select1 <- numVector[c(T,T,F,T,F,F,T)]; select1
select2 <- select1[c(1,4)]; select2

# 相當於
numPositions <- c(1,4)
wantItOrNot <- c(T,T,F,T,F,F,T)
numVector[wantItOrNot][numPositions]
```


```{r}
majors <- c("經濟學系","經濟學系","社會學系","社工系","經濟學系")
names <- c("小英", "小美", "大雄","阿華", "阿尼")
gender <- c("F","F","M","F","M")
```


```{r}
str(get1, max.level = 3)
```
```{r}
get1$`108-1`[[1]]$teacher
```


```{r}
str(get2, max.level=4)
```


```{r}
get2$`學期`$`108-1`[[1]]$teacher
```













