---
title: "List"
author: "林茂廷"
date: "3/31/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## List

```{r}
vectorExample <- c(2, 6, 7)
listExample <- list(2, 6, 7)

print(vectorExample)
print(listExample)
```

每個元素值可以是不同type的物件值。
```{r}
# 用vector儲存
c("2020-03-31T13:40:55Z", 
  "一芳", 
  "2", 
  "水果茶")

# 用list儲存
library(lubridate)
`小明交易1` <- list(
  ymd_hms("2020-03-31T13:40:55Z"), # Date/Time class
  "一芳", # character
  2, # numeric
  "水果茶" # character
)
print(`小明交易1`)
```

物件值可以是vector形式，也可以list。
```{r}
# 用vector
c(
  c("108學年第1學期", "高級會計學",  "高等統計學"), #向量1
  c("108學年第2學期", "食在拉丁美洲") #向量2
)
```

```{r}
# 用list
list(
  c("108學年第1學期", "高級會計學",  "高等統計學"), #向量1
  c("108學年第2學期", "食在拉丁美洲") #向量2
)
```
```{r}
# list含兩個vectors
`小明108學年課表A` <- list(
  c("108-1","高級會計學","高等統計學"),
  c("108-2","食在拉丁美洲")
)
print(`小明108學年課表A`)
```

```{r}
# list含兩個lists
`小明108學年課表B` <- list(
  list("108-1","高級會計學","高等統計學"),
  list("108-2","食在拉丁美洲")
)
print(`小明108學年課表B`)
```


```{r}
# list含兩個lists
`小明108學年課表C` <- list(
  list(
    c("108-1"),
    c("高級會計學","高等統計學")
    ),
  list(
    c("108-2"),
    c("食在拉丁美洲")
  )
)
print(`小明108學年課表C`)
```


物件值可以取名。
```{r}
`小明108學年課表D` <- list(
  `上學期`=list(
    semester=c("108-1"),
    c("高級會計學","高等統計學")
    ),
  list(
    semester=c("108-2"),
    courses=c("食在拉丁美洲")
  )
)
print(`小明108學年課表D`)
```


## Github Commit

```{r}
commit <- list(
  author = list(
    name="Martin老師", 
    email="mtlin@gm.ntpu.edu.tw", 
    time=ymd_hms("2020-03-25T07:17:40Z")),
  committer = list(
    name="emilyluckey",
    email="emily007@gmail.com",
    time=ymd_hms("2020-03-26T08:18:40Z")
  ),
  message = "update"
)
print(commit)
# 
#   committer = , 
#   message = 
# )
```


```{r}
browseURL("https://api.github.com/repos/tpemartin/108-2-56-inclass-practice/commits") 
```


```{r}
library(jsonlite) # 不少同學這行會有Error，還記得如何排除嗎？
toJSON(commit)
```
```{r}
library(jsonlite)
fromJSON("https://opendata.cwb.gov.tw/fileapi/v1/opendataapi/F-C0032-001?Authorization=rdec-key-123-45678-011121314&format=JSON") ->
  weather_next36hours
```


## 3.7

```{r}
save(commit,listExample,`小明108學年課表D`, file="today.Rda")
```

```{r}
load("today.Rda")
```



```{r}
`今天和明天的氣溫`<-list(list(
  `今天日期`=("2020-03-31"),
  `明天日期`=("2020-04-01"),
  list(city="台北市",highesttp=25,lowsttp=18),
  city="新北市",highesttp=24,lowsttp=15)
           )

print(`今天和明天的氣溫`)
```


```{grViz}
digraph weather_graph {
  node
  a [label="今明天氣"]
  b1 [label="今天日期"]
  b2 [label="明天日期"]
  b3 [label="各地預報"]
  c1 [label="台北市預報"]
  c2 [label="新北市預報"]
  
  a -> {b1 b2 b3}
  b3 -> {c1 c2}
  
}
```


```{r}
library(DiagrammeR)
grViz(
'
digraph weather_graph {
  node
  a[label="@@1今明天氣"]
  b1[label="@@2今天日期"]
  b2[label="@@3明天日期"]
  b3[label="@@4各地預報"]

  
  a -> {b1 b2 b3}
  b3 -> {c1 c2}
  
}'  
)
```

  c1[label="@@5台北市預報"]
  c2[label="@@6新北市預報"]

從底部開始架起
```{r}
`台北市預報元素值` <- 
  list(
    city="台北市",
    high=25,
    low=18
  )
`新北市預報元素值` <- 
  list(
    city="新北市",
    high=24,
    low=15
  )

`各地預報元素值` <-
  list(
    `台北市預報`=`台北市預報元素值`,
    `新北市預報`=`新北市預報元素值`
  )

#library(lubridate)
`今明天氣` <-
  list(
    `今天日期`=lubridate::ymd_hms("2020-03-31 14:22:55"),
    `明天天氣`=lubridate::ymd_hms("2020-04-01 15:22:43"),
    `各地預報`=`各地預報元素值`
  )

print(`今明天氣`)


ggplot(`今明天氣`)
```




```{r}
`今明天氣`
```


```{r}
a <- list(
 list("個體經濟學","總體經濟學"),
  list("作業研究")
)
a

a <- list(
  b ,
  c 
)
```

```{r}
a[[1]][[1]]
```


